// templates/svelte-ts/src/lib/components/connect-wallet-components/Wallet.svelte
<script lang='ts'>
import { createEventDispatcher } from 'svelte';
import type { BaseWallet } from "@polkadot-onboard/core";
import useConnectedWalletStore from "../../store/useConnectWalletStore";

    export let wallet: BaseWallet; // Receive wallet as a prop


const connectWalletHandler = async () => {
    console.log("wallet clicked!");

   $useConnectedWalletStore.connectWallet(wallet);
  };

</script>

<div>
    <div class="wallet-option">
        {#if wallet?.metadata?.iconUrl}
        <img
          width={25}
          height={25}
          src={wallet.metadata.iconUrl}
          alt="wallet icon"
        />
        {/if}

      <div>{`${wallet.metadata.title}`}</div>

      <button type="button" on:click={connectWalletHandler}>
        Connect Wallet
      </button>
    </div>
</div>

<style>
  /* Add your styles here */
</style>

// templates/react-js/src/components/connect-wallet-components/Wallet.jsx
import { memo } from "react";
import useConnectedWalletStore from "../../zustand/useConnectWalletStore";
import PropTypes from "prop-types";

const Wallet = ({ wallet }) => {
  const { connectWallet } = useConnectedWalletStore();

  const connectWalletHandler = async () => {
    connectWallet(wallet);
  };

  return (
    <div className="wallet-option">
      {wallet?.metadata?.iconUrl && (
        <img
          width={25}
          height={25}
          src={wallet.metadata.iconUrl}
          alt="wallet icon"
        />
      )}
      <div>{`${wallet.metadata.title}`}</div>

      <button type="button" onClick={connectWalletHandler}>
        Connect Wallet
      </button>
    </div>
  );
};

Wallet.propTypes = {
  wallet: PropTypes.shape({
    metadata: PropTypes.shape({
      iconUrl: PropTypes.string,
      title: PropTypes.string,
    }),
  }).isRequired,
};

const MemoWallet = memo(Wallet);
export default MemoWallet;
