// templates/react-js/src/App.jsx
import "./App.css";
import ReactLogo from "./components/logos/react";
import ViteLogo from "./components/logos/vite";
import JavaScriptLogo from "./components/logos/javascript";
import useConnectedWalletStore from "./zustand/useConnectWalletStore";
import { useEffect, useState } from "react";
function App() {
  const { connectedWallet, api, connectedAccount } = useConnectedWalletStore();

  const [balance, setBalance] = useState(0);
  const [chain, setChain] = useState("");

  useEffect(() => {
    async function getChainData() {
      if (!api) return;
      const [chain, nodeName] = await Promise.all([
        api.rpc.system.chain(),
        api.rpc.system.name(),
      ]);
      setChain(`${chain} - ${nodeName}`);

      if (connectedAccount?.address) {
        const chainToken = await api.registry.chainTokens[0];
        api.query.system.account(connectedAccount?.address, (res) => {
          setBalance(`${res.data.free.toHuman()} ${chainToken}`);
        });
      }
    }
    getChainData();
  }, [api, connectedAccount]);

  async function signTransaction() {
    try {
      const chain = await api.rpc.system.chain();
      if (api && connectedAccount?.address && connectedWallet.signer) {
        const signer = connectedWallet.signer;
        const decimals = api.registry.chainDecimals[0];
        console.log(decimals);
        console.log(api.registry);

        await api.tx.system
          .remark("Hello World")
          .signAndSend(connectedAccount.address, { signer }, () => {
            // do something with result
          });
      }

      console.log(chain);
    } catch (err) {
      alert("Error signing transaction");
      console.log(err);
    }
  }
  return (
    <main className="page-body">
      <div className="logos-container">
        <JavaScriptLogo className="logo" />

        <h1>+</h1>

        <ReactLogo className="logo" />

        <h1>+</h1>

        <ViteLogo className="logo" />

        <h1>+</h1>

        <img src="/images/polkadot-logo.svg" alt="Polkadot" className="logo" />
      </div>

      {connectedWallet?.isConnected ? (
        <div className="sample-transaction">
          {connectedAccount?.address && (
            <p className="balance-label">Balance: {balance}</p>
          )}
          <button
            type="button"
            onClick={() => {
              signTransaction();
              console.log("Hello World");
            }}
          >
            Sign Transaction
          </button>

          <p className="chain-label">{chain}</p>
        </div>
      ) : (
        <div>
          <h4>Conntect your Wallet</h4>
        </div>
      )}

      <p className="instructions">
        Make Changes to <code>/src/App.jsx</code>
      </p>
    </main>
  );
}

export default App;

// templates/svelte-ts/src/App.svelte
<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  import polkadotLogo from './images/polkadot-logo.svg'
  import viteLogo from '/vite.svg'
  import typescriptLogo from './typescript.svg'
  import useConnectedWalletStore from './lib/store/useConnectWalletStore'
  import { setWallets } from './lib/components/contexts/wallets.context';

  const api = $useConnectedWalletStore.api
  const connectedAccount = $useConnectedWalletStore.connectedAccount
  const connectedWallet = $useConnectedWalletStore.connectedWallet

  let balance: number;
  let chainToken: string;
  let chain: string;

  setWallets()

    async function getChainData() {
      if (!api) return;
      const [_chain, _nodeName] = await Promise.all([
        api.rpc.system.chain(),
        api.rpc.system.name(),
      ]);
      chain = `${_chain} - ${_nodeName}`;

      if (connectedAccount?.address) {
         chainToken = api.registry.chainTokens[0];
        api.query.system.account(
          connectedAccount?.address,
          (res: { data: { free: { toHuman: () => number; }; }; }) => {
            balance = res.data.free.toHuman()
          }
        );
      }
    }

  async function signTransaction() {
    try {
      if (api && connectedAccount?.address && connectedWallet?.signer) {
        const signer = connectedWallet.signer;
        const decimals = api.registry.chainDecimals[0];
        console.log(decimals);
        console.log(api.registry);

        await api.tx.system
          .remark("Hello World")
          .signAndSend(connectedAccount.address, { signer }, () => {
            // do something with result
          });
      }
    } catch (err) {
      alert("Error signing transaction");
      console.log(err);
    }
  }
  // biome-ignore lint/suspicious/noConfusingLabels: <explanation>
  // biome-ignore lint/correctness/noUnusedLabels: <explanation>
    $: {
    if(api) {
      getChainData()
      console.log("Got Chain Details")
    }
  }
</script>
    <main class="page-body">
      <div class="logos-container">
      <img src={typescriptLogo} class="logo svelte" alt="Svelte Logo" />

        <h1>+</h1>

      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />

        <h1>+</h1>

      <img src={viteLogo} class="logo svelte" alt="Svelte Logo" />

        <h1>+</h1>

        <img src={polkadotLogo} alt="Polkadot" class="logo" />
      </div>

      {#if $useConnectedWalletStore.connectedWallet?.isConnected}
        <div class="sample-transaction">

          {#if $useConnectedWalletStore.connectedAccount?.address}
            <p class="balance-label">
              Balance: {balance} {chainToken}
            </p>            
          {/if}
          <button
            type="button"
            on:click={() => {
              signTransaction();
            }}
          >
            Sign Transaction
          </button>

          <p class="chain-label">{chain}</p>
        </div>
        {:else}
        <div>
          <h4>Conntect your Wallet</h4>
        </div>
      {/if}
      <p class="instructions">
        Make Changes to <code>/src/App.svelte</code>
      </p>
    </main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
</style>
