// templates/frontend/react-ts/src/App.tsx
import React, { useEffect, useState } from "react";
import ReactLogo from "./components/logos/react";
import TypeScriptLogo from "./components/logos/typescript";
import ViteLogo from "./components/logos/vite";
import useConnectedWalletStore from "./zustand/useConnectWalletStore";
import { ArrowRight } from "lucide-react";

function App() {
  const { connectedWallet, api, connectedAccount } = useConnectedWalletStore();

  const [balance, setBalance] = useState<number>(0);
  const [chainToken, setChainToken] = useState<string>("");
  const [chain, setChain] = useState<string>("");

  useEffect(() => {
    async function getChainData() {
      if (!api) return;
      const [chain, nodeName] = await Promise.all([
        api.rpc.system.chain(),
        api.rpc.system.name(),
      ]);
      setChain(`${chain} - ${nodeName}`);

      if (connectedAccount?.address) {
        const chainToken = api.registry.chainTokens[0];
        api.query.system.account(
          connectedAccount?.address,
          (res: {
            data: { free: { toHuman: () => React.SetStateAction<number> } };
          }) => {
            setBalance(res.data.free.toHuman());
            setChainToken(chainToken);
          }
        );
      }
    }
    getChainData();
  }, [api, connectedAccount]);

  async function signTransaction() {
    try {
      if (api && connectedAccount?.address && connectedWallet?.signer) {
        const signer = connectedWallet.signer;

        await api.tx.system
          .remark("Hello World")
          .signAndSend(connectedAccount.address, { signer }, () => {
            // do something with result
          });
      }
    } catch (err) {
      alert("Error signing transaction");
      console.log(err);
    }
  }

  return (
    <main className="min-h-screen bg-gradient-to-b from-purple-900 to-purple-700 text-white py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-center items-center space-x-6 mb-12">
          <TypeScriptLogo className="w-16 h-16" />
          <ArrowRight size={24} />
          <ReactLogo className="w-16 h-16" />
          <ArrowRight size={24} />
          <ViteLogo className="w-16 h-16" />
          <ArrowRight size={24} />
          <img
            src="/images/polkadot-logo.svg"
            alt="Polkadot"
            className="w-16 h-16"
          />
        </div>

        <div className="bg-white/10 backdrop-blur-md rounded-lg p-8 mb-8">
          {connectedWallet?.isConnected ? (
            <div className="space-y-4">
              {connectedAccount?.address && (
                <>
                  <p className="text-xl font-semibold">
                    Balance: {balance} {chainToken}
                  </p>

                  <button
                    type="button"
                    onClick={signTransaction}
                    className="bg-purple-500 hover:bg-purple-600 text-white font-bold py-2 px-4 rounded transition duration-300"
                  >
                    Sign Transaction
                  </button>
                </>
              )}
              <p className="text-sm opacity-75">{chain}</p>
            </div>
          ) : (
            <div className="text-center">
              <h4 className="text-2xl font-bold mb-4">Connect your Wallet</h4>
              <p className="opacity-75">
                Please connect your wallet to interact with the dApp.
              </p>
            </div>
          )}
        </div>

        <p className="text-center text-lg">
          Make changes to{" "}
          <code className="bg-purple-800 px-2 py-1 rounded">src/App.tsx</code>
        </p>
      </div>
    </main>
  );
}

export default App;

// templates/svelte-ts/src/App.svelte
<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  import polkadotLogo from '/images/polkadot-logo.svg'
  import viteLogo from '/vite.svg'
  import typescriptLogo from './assets/typescript.svg'
  import useConnectedWalletStore from './lib/store/useConnectWalletStore'
  import useWalletsStore from './lib/store/useWalletsStore'
  import Header from "./lib/components/Header.svelte";
  import { setWallets } from './lib/components/contexts/wallets.context';
  import { onMount } from 'svelte';

  const api = $useConnectedWalletStore.api
  const connectedAccount = $useConnectedWalletStore.connectedAccount
  const connectedWallet = $useConnectedWalletStore.connectedWallet

  let balance: number;
  let chainToken: string;
  let chain: string;

  // setWallets()

    async function getChainData() {
      if (!api) return;
      const [_chain, _nodeName] = await Promise.all([
        api.rpc.system.chain(),
        api.rpc.system.name(),
      ]);
      chain = `${_chain} - ${_nodeName}`;

      if (connectedAccount?.address) {
         chainToken = api.registry.chainTokens[0];
        api.query.system.account(
          connectedAccount?.address,
          (res: { data: { free: { toHuman: () => number; }; }; }) => {
            balance = res.data.free.toHuman()
          }
        );
      }
    }

  async function signTransaction() {
    try {
      if (api && connectedAccount?.address && connectedWallet?.signer) {
        const signer = connectedWallet.signer;
        const decimals = api.registry.chainDecimals[0];
        console.log(decimals);
        console.log(api.registry);

        await api.tx.system
          .remark("Hello World")
          .signAndSend(connectedAccount.address, { signer }, () => {
            // do something with result
          });
      }
    } catch (err) {
      alert("Error signing transaction");
      console.log(err);
    }
  }
  // biome-ignore lint/suspicious/noConfusingLabels: <explanation>
  // biome-ignore lint/correctness/noUnusedLabels: <explanation>
    $: {
    if(api) {
      getChainData()
      console.log("Got Chain Details")
    }
  }

  onMount(() => {
      $useWalletsStore.setWallets()
  })
</script>
      <Header />
    <main class="page-body">
      <div class="logos-container">
      <img src={typescriptLogo} class="logo" alt="Svelte Logo" />

        <h1>+</h1>

      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />

        <h1>+</h1>

      <img src={viteLogo} class="logo" alt="Svelte Logo" />

        <h1>+</h1>

        <img src={polkadotLogo} alt="Polkadot" class="logo" />
      </div>

      {#if $useConnectedWalletStore.connectedWallet?.isConnected}
        <div class="sample-transaction">

          {#if $useConnectedWalletStore.connectedAccount?.address}
            <p class="balance-label">
              Balance: {balance} {chainToken}
            </p>     
            
          <button
            type="button"
            on:click={() => {
              signTransaction();
            }}
          >
            Sign Transaction
          </button>
          {/if}


          <p class="chain-label">{chain}</p>
        </div>
        {:else}
        <div>
          <h4>Connect your Wallet</h4>
        </div>
      {/if}
      <p class="instructions">
        Make Changes to <code>/src/App.svelte</code>
      </p>
    </main>

<style>
  .logo {
    height: 6em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
</style>
