// templates/react-ts/src/components/connect-wallet-components/ConnectWalletButton.tsx
import { useState } from "react";
import Wallets from "./Wallets";
import React from "react";

export default function ConnectWalletButton() {
  const [showWallets, setShowWallets] = useState(false);

  return (
    <div>
      <button
        type="button"
        onClick={() => {
          setShowWallets(!showWallets);
        }}
      >
        {showWallets ? "Hide Wallets" : "Show Wallets"}
      </button>

      {showWallets && (
        <dialog open>
          <Wallets />
        </dialog>
      )}
    </div>
  );
}

// templates/svelte-ts/src/lib/components/connect-wallet-components/ConnectWalletButton.svelte
<script lang='ts'>
import Wallets from "./Wallets.svelte";
    let showWallets = false;

    const toggleShowWallets = () => {
        showWallets = !showWallets;
    }

</script>

<main>
    <div>
      <button
        type="button"
        on:click={() => {
          toggleShowWallets()
        }}
      >
        {showWallets ? "Hide Wallets" : "Show Wallets"}
      </button>

        {#if showWallets}
            <dialog open>
              <Wallets />
            </dialog>
        {/if}

    </div>
</main>

<style>
  /* Add your styles here */
</style>
